### ISSUE TITLE
目前的master可以发布一个2.5版本吗？

### ISSUE THREAD

**Issue by simon-shi87** [EalenXie/aop-log#11]
目前的master可以发布一个2.5版本吗？一些bug修复了，可以发布了吧？

**Comment by simon-shi87** [comment]
发现无法获取 header的内容

**Comment by EalenXie** [comment]
> 目前的master可以发布一个2.5版本吗？一些bug修复了，可以发布了吧？

感谢提出建议。2.5v的版本即刻发布。
另外无法获取header的内容是什么情况呢？

**Comment by simon-shi87** [comment]
> > 目前的master可以发布一个2.5版本吗？一些bug修复了，可以发布了吧？
> 
> 感谢提出建议。2.5v的版本即刻发布。
> 另外无法获取header的内容是什么情况呢？

这个可能是我本地打包的问题，我用master的分支打了个包测试，获取不到header

**Comment by EalenXie** [comment]
v2.5已发布
