### ISSUE TITLE
[bug]异步模式下，方法抛出异常后日志不打印

### ISSUE THREAD

**Issue by zorohu** [EalenXie/aop-log#12]
如题，使用异步模式的时候日志不打印。不使用异步模式日志正常输出
以下是我的测试用例

![image](https://user-images.githubusercontent.com/24402746/127660257-4b5c6bba-1134-449c-ae14-9f3b15e53f18.png)

![image](https://user-images.githubusercontent.com/24402746/127659919-8ed18318-59bd-4344-8393-9d22ec8bccd5.png)

**Comment by EalenXie** [comment]
你好，我用同样的版本和模拟和你的代码一样进行测试没有发现问题哦，是否是你的JSONUtil方法出了问题呢。

**Comment by zorohu** [comment]
> 你好，我用同样的版本和模拟和你的代码一样进行测试没有发现问题哦，是否是你的JSONUtil方法出了问题呢。

不好意思，经过排查发现。并不是没有打印，而是IDEA的控制台把抛出异常的日志自动收缩了。
