### ISSUE TITLE
Before the method

### ISSUE THREAD

**Issue by zorohu** [EalenXie/aop-log#15]
需要在方法执行之前执行一些操作，目前支持吗？

**Comment by EalenXie** [comment]
不太明白你的意思哦，`AopLog`实现不就是个AOP的环绕通知么。

**Comment by zorohu** [comment]
就是我目前使用这个注解，只会在一个请求结束后才打印出日志。如果我想在请求进来的时候打印入参，请求返回之后打印出参。
我看了下源码，貌似没有这种类似的扩展，所以提了这个issues。不知道我这样表达清楚了没有
