### ISSUE TITLE
Bug提交

### ISSUE THREAD

**Issue by sivern** [EalenXie/aop-log#17]
AopLogProcessor中     if (!aopLog.isLogOnErr() || !data.isSuccess())  该判断是否是一个bug，理论上应该是   if (!aopLog.isLogOnErr() && !data.isSuccess()) 的关系

**Comment by sivern** [comment]
该bug会使配置只在异常时打印日志的配置项失效，已验证

**Comment by EalenXie** [comment]
十分感谢指点，但不是bug，`logOnErr==true` 代表仅当发生异常时才记录，`!aopLog.isLogOnErr() `等同于`logOnErr == false`，即无论是否发生异常都会记录，此条件不成立时(即`logOnErr ==true`时) ，仅仅只需要判断 `data.isSuccess()==false`即可，故判断条件为`!aopLog.isLogOnErr() || !data.isSuccess()`
