### ISSUE TITLE
LogData对象里面args对象自动toString

### ISSUE THREAD

**Issue by Curtain-Wang** [EalenXie/aop-log#20]
![image](https://user-images.githubusercontent.com/49394182/150897334-0d73c435-c660-4c7e-a903-cbbfceaa1ee8.png)
在与前端调试的时候发现，LogData对象里面args参数，是String类型的，而不是实际的它对象类型。像是对象toString后的结果。用postman调试的时候是正常的，什么类型就是什么类型，不会是toString后的结果。
请教一下~

**Comment by Curtain-Wang** [comment]
环境： Springboot: 2.3.12.RELEASE
            aop-log： 2.5

**Comment by EalenXie** [comment]
> 环境： Springboot: 2.3.12.RELEASE aop-log： 2.5

对args数据抽取逻辑是[DataExtractor#getArgs](DataExtractorhttps://github.com/EalenXie/aop-log/blob/master/src/main/java/com/github/DataExtractor.java)方法，如果请求头的`content/type`不为`application/json`，目前的处理逻辑args就会以a=xx&b=xxx的形式返回。这里的xxx参数会被toString()，这部分处理逻辑我也正在后期版本考虑优化。

**Comment by Curtain-Wang** [comment]
> > 环境： Springboot: 2.3.12.RELEASE aop-log： 2.5
> 
> 对args数据抽取逻辑是DataExtractor#getArgs方法，如果请求头的`content/type`不为`application/json`，目前的处理逻辑args就会以a=xx&b=xxx的形式返回。这里的xxx参数会被toString()，这部分处理逻辑我也正在后期版本考虑优化。
OK 谢谢回复~

**Comment by Curtain-Wang** [comment]
OK, 感谢回复~

**Comment by Curtain-Wang** [comment]
> 对args数据抽取逻辑是DataExtractor#getArgs方法，如果请求头的`content/type`不为`application/json`，目前的处理逻辑args就会以a=xx&b=xxx的形式返回。这里的xxx参数会被toString()，这部分处理逻辑我也正在后期版本考虑优化。

OK~感谢回复
