### ISSUE TITLE
objectMapper.writeValueAsString(o)报错It is illegal to call this method if the current request is not in asynchronous mode

### ISSUE THREAD

**Issue by yalongwan** [EalenXie/aop-log#23]
![image](https://user-images.githubusercontent.com/16027160/171317582-cb02d2b1-2964-4396-8146-3893217d3cd9.png)

**Comment by EalenXie** [comment]
收集器例子只是提供参考说明,真正的收集过程请不要完全照搬,`ObjectMapper.writeValueAsString`没有考虑到LogData不能被序列化的情况
