### ISSUE TITLE
业务层中使用了LogData.step()，并在末尾执行LogData.removeCurrent()，收集器里的LogData.getCostTime() == 0

### ISSUE THREAD

**Issue by arccode** [EalenXie/aop-log#3]
业务层使用@AopLog(type = "描述", stackTraceOnErr = true)进行注解，并在业务末尾进行清理（LogData.removeCurrent()）；采用自定义收集器方式发现LogData.getCostTime() == 0， 如果不清理LogData.getCostTime() 数据正常

**Comment by EalenXie** [comment]
在使用了@AopLog的方法里面无需调用LogData.removeCurrent()，AopLog会自动帮忙释放

**Comment by arccode** [comment]
已解决
