### ISSUE TITLE
获取IP的过程非常耗时

### ISSUE THREAD

**Issue by jrsports** [EalenXie/aop-log#4]
打断点发现InetAddress.getLocalHost().getHostAddress()方法要执行将近5-8秒，怎么处理

**Comment by EalenXie** [comment]
嗯，这个InetAddress.getLocalHost()是Java原生方法的坑，之前我也没碰到过，这个方法会通过内核指令获取本机host，所以如果本机hosts配置被改动过的话，再需要经过DNS解析本机ip的话，获取会很慢。
解决方法暂时参考 : https://www.cnblogs.com/jizhao/p/4081675.html
我这个问题我会记下优化修复的。
感谢提出意见。。

**Comment by jrsports** [comment]
好的，可以优化一下这个方法，或者加个注解允许不获取IP~

**Comment by EalenXie** [comment]
2.2通过遍历网卡获取ip地址
